version: '3'

volumes:
  mysql_data: {}

services:
  db:
    image: mysql
    container_name: mysql_container
    volumes:
      - mysql_data:/var/lib/postgres/data

    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    
    environment:
      
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mobo
      - MYSQL_USER=mobo
      - MYSQL_PASSWORD=mobo
    
    restart: always

    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10

  django:
    container_name: django_container
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - ./:/app/
    command: ["./manage.py", "runserver", "0:8000"]
    environment:
     - DJANGO_DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - 8000:8000