# Generated by Django 2.2.4 on 2022-11-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
